### ISSUE TITLE
Auto-update tutorial example module version upon release

### ISSUE THREAD

**Issue by picatz** [picatz/terraform-google-nomad#14]
Run a GitHub Actions workflow upon a new version [release](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release) to keep the tutorial content up-to-date.

```yaml
on:
  release:
    types: [published]
```
